/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\models\kenney_car-kit\glb-format\sedan-sports.glb --transform --meta
Files: .\public\assets\models\kenney_car-kit\glb-format\sedan-sports.glb [177.68KB] > C:\Users\nmdex\Documents\Projects\rally-box\sedan-sports-transformed.glb [13.4KB] (92%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SedanSports(props) {
  const { nodes, materials } = useGLTF(
    "/assets/models/kenney_car-kit/glb-format/sedan-sports-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["wheel-back-right"].geometry}
        material={materials.colormap}
        position={[-0.3, 0.3, -0.66]}
        userData={{ name: "wheel-back-right" }}
      />
    </group>
  );
}

useGLTF.preload(
  "/assets/models/kenney_car-kit/glb-format/sedan-sports-transformed.glb",
);
